In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('call_activity.csv')
df

,call_id,caller,receiver,start_time,end_time,duration_seconds,status
0,1,85512345678,85598765432,2026-05-14 09:15:23,2026-05-14 09:17:10,107,Completed
1,2,85511122334,85599887766,2026-05-14 10:02:45,2026-05-14 10:03:05,20,Missed
2,3,85522334455,85566778899,2026-05-14 11:30:00,2026-05-14 11:45:12,912,Completed
3,4,85533445566,85577889900,2026-05-14 12:05:10,2026-05-14 12:05:10,0,Declined
4,5,85544556677,85588990011,2026-05-14 13:20:33,2026-05-14 13:25:01,268,Completed
5,6,85555667788,85599001122,2026-05-14 14:40:00,2026-05-14 14:41:15,75,Missed

In [4]:
df.head()

,call_id,caller,receiver,start_time,end_time,duration_seconds,status
0,1,85512345678,85598765432,2026-05-14 09:15:23,2026-05-14 09:17:10,107,Completed
1,2,85511122334,85599887766,2026-05-14 10:02:45,2026-05-14 10:03:05,20,Missed
2,3,85522334455,85566778899,2026-05-14 11:30:00,2026-05-14 11:45:12,912,Completed
3,4,85533445566,85577889900,2026-05-14 12:05:10,2026-05-14 12:05:10,0,Declined
4,5,85544556677,85588990011,2026-05-14 13:20:33,2026-05-14 13:25:01,268,Completed

In [5]:
df.tail()

,call_id,caller,receiver,start_time,end_time,duration_seconds,status
1,2,85511122334,85599887766,2026-05-14 10:02:45,2026-05-14 10:03:05,20,Missed
2,3,85522334455,85566778899,2026-05-14 11:30:00,2026-05-14 11:45:12,912,Completed
3,4,85533445566,85577889900,2026-05-14 12:05:10,2026-05-14 12:05:10,0,Declined
4,5,85544556677,85588990011,2026-05-14 13:20:33,2026-05-14 13:25:01,268,Completed
5,6,85555667788,85599001122,2026-05-14 14:40:00,2026-05-14 14:41:15,75,Missed

In [7]:
type(df)

pandas.DataFrame

In [15]:
df['caller']

0    85512345678
1    85511122334
2    85522334455
3    85533445566
4    85544556677
5    85555667788
Name: caller, dtype: int64

In [16]:
type(df['caller'])

pandas.Series

## CREATE A DATAFRAM FROM A DICTIONARY